### ISSUE TITLE
Clearer git status

### ISSUE THREAD

**Issue by RobertAudi** [supercrabtree/k#22]
First of all: Awesome job with the little script :clap:

As much as I love the git integration, it's kind of hard to take advantage of it. What I would expect from such a feature would be to have an instant overview of the state of a repository. Right now the representation is too minimalistic and a bit unclear. I'm still thinking about potential solutions to suggest something, I'll update this issue as soon as I think of something.

**Comment by supercrabtree** [comment]
"have an instant overview of the state of a repository"

try `git status -s`

This tool is more to sprinkle your ls listings with some useful extra info
