### ISSUE TITLE
I don't want warnings about permission for symlinks

### ISSUE THREAD

**Issue by yu-ichiro** [supercrabtree/k#25]
Hi! I'm a newbie to this program.
Thanks for the program! It's awesome.

I found out that this program warns you if you got a file with a bad permission setting, but symlinks don't need that, and besides, I can't chmod the symlinks either.

If you could put a logic before putting out the warning that will be great :)

**Comment by supercrabtree** [comment]
Ok, good point, I'll get this fixed soon, gimme a few days
