### ISSUE TITLE
files and directories with spaces printing with quotes

### ISSUE THREAD

**Issue by chrstphrknwtn** [supercrabtree/k#30]
Title says it all really, I've had a quick look into why this is happening... but not found anything.

![screen shot 2015-01-28 at 10 29 10](https://cloud.githubusercontent.com/assets/1848516/5935210/8c728340-a6d8-11e4-9b84-4cc97c3055a4.png)

**Comment by zirrostig** [comment]
So the quotes are coming from line 409, removing it, fixes this problem, but then all paths are pri
`NAME="${(q-)${NAME##*/}//$'\e'/\\e}"`
It appears that removing `(q-)` from it fixes the problem but I'm not sure if that breaks anything else, the comment preceeding it, would make it seem like it will.
