### ISSUE TITLE
unexpected chpwd() calls from cd inside the command

### ISSUE THREAD

**Issue by yu-ichiro** [supercrabtree/k#32]
The new update is awesome! Thanks to all the contributors.

Everything is working fine, but when it lists directories, it shows what's inside too.
It's not that pretty, but it's working, so that is not that big of a deal.
But the concerning part is that it's occuring because I'm setting my own chpwd() to show the directory contents when moving into a directory. This means that the command will call chpwd() even when we didn't change working directory.

When we use this command, we are listing the directory contents, but not actually changing directories. 
So changing directory inside a command, even if going back to the original directory, might cause unexpected things to happen.

I don't quite know how we can work it around though.
Are there any possible solutions for this?

**Comment by supercrabtree** [comment]
I didn't write this feature, so I am not sure of a workaround, perhaps @zirrostig can shed some light?

**Comment by zirrostig** [comment]
I entirely forgot about the zsh builtin hooks, A quick solution is to use `cd -q` in the code so those won't get called, its not the prettiest solution, but it should fix it for now.
