### ISSUE TITLE
how to disable git status

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [supercrabtree/k#37]
I noticed that k is order of magnitude slower than ls #28
After a quick reading of the issues seems that the slowliness is from git status.
How i disable the git status check? I'm interested in file size and time only.

**Comment by zirrostig** [comment]
```sh
k --no-vcs
```
Will prevent k from doing any git related stuff. I would just set up an alias to always set that flag. Other flags and usage can be seen with 
```sh
k --help
```

**Comment by Alessandro-Barbieri** [comment]
Aliased as
```
alias k='k -h --no-vcs'
```
